### ISSUE TITLE
crash in 3-asm: ovlp_to_graph.py  

### ISSUE THREAD

**Issue by rfinkers** [cschin/Peregrine#18]
specifically in the script/step: ovlp_to_graph.py I'm running into the following error:

AttributeError: 'DiGraph' object has no attribute 'node'

Googling suggests an issue with networkx? which is at version 2.4 in my conda based install. Any suggestions / which file's are needed for debug?

**Comment by cschin** [comment]
This is a duplicate from #19. We will track the issue there.
