### ISSUE TITLE
Null pointer error during installation 

### ISSUE THREAD

**Issue by alima90** [cschin/Peregrine#2]
Hi

I want to use Peregrine, however, Null pointer error was occurred during installation
In detail, the error was occured during compiling of shmr_map.c line 246 when i type 'make'

What's the problem? let me know
Thanks

**Comment by sifta** [comment]
Hi Alima90,
For most users, the suggestion is to get the code directly from dockerhub

docker pull cschin/peregrine

which gives you a prebuilt image and the follow the instructions under 'Running from Docker Image' in the readme.

**Comment by sifta** [comment]
@cschin Will make this clearer in the README

**Comment by cschin** [comment]
@sifta I just update the README... :) so can you take a look and see if we can close this one.

**Comment by sifta** [comment]
the text looks good, but the link is broken.  Try this one. 

https://hub.docker.com/r/cschin/peregrine/builds

**Comment by sifta** [comment]
yep.  made a small mistake in pointing to builds instead of tags, but fixed this as well.
