### ISSUE TITLE
Accuracy column in preads.ovl

### ISSUE THREAD

**Issue by mrvollger** [cschin/Peregrine#21]
Hi Jason,

Is the 4th column of `preads.ovl` an estimated identity, or the actual overlap identity? 

Thanks!
Mitchell

**Comment by cschin** [comment]
It should be considered as an estimated accuracy.

**Comment by mrvollger** [comment]
I see. Does PG ever calculate DP overlaps before the assembly stage or is it based on SHIMMERs and estimated overlaps only until consensus step?

**Comment by cschin** [comment]
@mrvollger  it does do alignment/overlap confirmation, It uses Gene Myers O(ND) alignment algorithm. The complexy is O(ND), N ~=sequence lengths, D=differences between the twe sequences. It is fast, but the difference is not the same as DP based methods. That is why I say it is “estimated”.

**Comment by mrvollger** [comment]
I see, thanks for the clarification!
