### ISSUE TITLE
docker errors

### ISSUE THREAD

**Issue by bitcometz** [cschin/Peregrine#3]
Hello，

I docker run -i -t cschin/peregrine '/bin/bash' and met this errors:
/opt/entry.sh: line 4: pg_run.py: command not found

Best

**Comment by cschin** [comment]
@bitcometz the DockerHub build system or my build script for it might have some issue. Try this build ` docker run -i -t cschin/peregrine:0.1.5.2 '/bin/bash'`.  (The latest will reserved for development, using a tagged version is better.)

**Comment by sifta** [comment]
@bitcometz  @cschin  The container is currently configured to launch pg_run.py based on the Dockerfile.  Therefore, you can't launch a bash shell into the container to poke around until it is already running an assembly.

**Comment by cschin** [comment]
@sifta Thanks. I saw similar thing before. I think the DockerHub auto-build set-up has some issue now. I had to push the tagged build to override the DockerHub once before. I like to investigate what is going some time later.

**Comment by cschin** [comment]
@sifta I think the last commit fixed the real problem. I am closing this issue now.

@bitcometz  as mentioned by @sifta the default "entrypoint" for the docker image is to run pg_run.py. 
This the canonical way to launch the assembler:
```
find /wd/chm13-fastq/ -name "*.fastq" | sort > chm13-seqdata.lst 

docker run -it -v /wd:/wd --user $(id -u):$(id -g) cschin/peregrine:0.1.5.0 asm \
    /wd/chm13-seqdata.lst 24 24 24 24 24 24 24 24 24 \ 
    --with-consensus --shimmer-r 3 --best_n_ovlp 8 \ 
    --output /wd/chm13-asm-r3-pg0.1.5.0 
```
Please read the README to adjust the concurrence setup for your computing node.  Depending on the amount of memory and CPUs that you have, you will need to adjust those for the optimized performance.
