### ISSUE TITLE
how to produced p_ctg_cns.fa by p_ctg.fa?

### ISSUE THREAD

**Issue by Ahahaha3** [cschin/Peregrine#41]
if i have a p_ctg.fa, just want to get a p_ctg_cns.fa. how to do that?

**Comment by cschin** [comment]
There is no standalone tool for this in Peregrine. However, there are a couple of internal module that you can use to achieve this. Please see the function run_cns () in `pg_run.py` at https://github.com/cschin/Peregrine/blob/008082af23b6d9d3ec45952984d8ed7c53c6b3c5/py/scripts/pg_run.py#L389
